package cr.ac.una.prograiv.project.domain;
// Generated 25/04/2017 03:07:58 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Aerolinea generated by hbm2java
 */
public class Aerolinea  implements java.io.Serializable {


     private Integer pkaIdAerolinea;
     private String nombre;
     private String email;
     private String telefono;
     private Date ultimaFecha;
     private String ultimoUsuario;
     private Set avions = new HashSet(0);

    public Aerolinea() {
    }

	
    public Aerolinea(String nombre, Date ultimaFecha, String ultimoUsuario) {
        this.nombre = nombre;
        this.ultimaFecha = ultimaFecha;
        this.ultimoUsuario = ultimoUsuario;
    }
    public Aerolinea(String nombre, String email, String telefono, Date ultimaFecha, String ultimoUsuario, Set avions) {
       this.nombre = nombre;
       this.email = email;
       this.telefono = telefono;
       this.ultimaFecha = ultimaFecha;
       this.ultimoUsuario = ultimoUsuario;
       this.avions = avions;
    }
   
    public Integer getPkaIdAerolinea() {
        return this.pkaIdAerolinea;
    }
    
    public void setPkaIdAerolinea(Integer pkaIdAerolinea) {
        this.pkaIdAerolinea = pkaIdAerolinea;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Date getUltimaFecha() {
        return this.ultimaFecha;
    }
    
    public void setUltimaFecha(Date ultimaFecha) {
        this.ultimaFecha = ultimaFecha;
    }
    public String getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(String ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }
    public Set getAvions() {
        return this.avions;
    }
    
    public void setAvions(Set avions) {
        this.avions = avions;
    }




}


