package cr.ac.una.prograiv.project.domain;
// Generated 19/05/2017 11:46:30 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Boleto generated by hbm2java
 */
public class Boleto  implements java.io.Serializable {


     private Integer pkaIdUsuario;
     private Integer ruta;
     private Integer usuario;
     private int numAsiento;
     private int numFila;
     private Date ultimafecha;
     private String ultimoUsuario;

    public Boleto() {
    }

    public Boleto(Integer ruta, Integer usuario, int numAsiento, int numFila, Date ultimafecha, String ultimoUsuario) {
       this.ruta = ruta;
       this.usuario = usuario;
       this.numAsiento = numAsiento;
       this.numFila = numFila;
       this.ultimafecha = ultimafecha;
       this.ultimoUsuario = ultimoUsuario;
    }
   
    public Integer getPkaIdUsuario() {
        return this.pkaIdUsuario;
    }
    
    public void setPkaIdUsuario(Integer pkaIdUsuario) {
        this.pkaIdUsuario = pkaIdUsuario;
    }
    public Integer getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Integer ruta) {
        this.ruta = ruta;
    }
    public Integer getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }
    public int getNumAsiento() {
        return this.numAsiento;
    }
    
    public void setNumAsiento(int numAsiento) {
        this.numAsiento = numAsiento;
    }
    public int getNumFila() {
        return this.numFila;
    }
    
    public void setNumFila(int numFila) {
        this.numFila = numFila;
    }
    public Date getUltimafecha() {
        return this.ultimafecha;
    }
    
    public void setUltimafecha(Date ultimafecha) {
        this.ultimafecha = ultimafecha;
    }
    public String getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(String ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }




}


